/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package scalago;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class PingPong extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PingPong\",\"namespace\":\"scalago\",\"fields\":[{\"name\":\"counter\",\"type\":\"long\"},{\"name\":\"name\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public long counter;
  @Deprecated public java.lang.CharSequence name;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public PingPong() {}

  /**
   * All-args constructor.
   */
  public PingPong(java.lang.Long counter, java.lang.CharSequence name) {
    this.counter = counter;
    this.name = name;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return counter;
    case 1: return name;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: counter = (java.lang.Long)value$; break;
    case 1: name = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'counter' field.
   */
  public java.lang.Long getCounter() {
    return counter;
  }

  /**
   * Sets the value of the 'counter' field.
   * @param value the value to set.
   */
  public void setCounter(java.lang.Long value) {
    this.counter = value;
  }

  /**
   * Gets the value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /** Creates a new PingPong RecordBuilder */
  public static scalago.PingPong.Builder newBuilder() {
    return new scalago.PingPong.Builder();
  }
  
  /** Creates a new PingPong RecordBuilder by copying an existing Builder */
  public static scalago.PingPong.Builder newBuilder(scalago.PingPong.Builder other) {
    return new scalago.PingPong.Builder(other);
  }
  
  /** Creates a new PingPong RecordBuilder by copying an existing PingPong instance */
  public static scalago.PingPong.Builder newBuilder(scalago.PingPong other) {
    return new scalago.PingPong.Builder(other);
  }
  
  /**
   * RecordBuilder for PingPong instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PingPong>
    implements org.apache.avro.data.RecordBuilder<PingPong> {

    private long counter;
    private java.lang.CharSequence name;

    /** Creates a new Builder */
    private Builder() {
      super(scalago.PingPong.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(scalago.PingPong.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.counter)) {
        this.counter = data().deepCopy(fields()[0].schema(), other.counter);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing PingPong instance */
    private Builder(scalago.PingPong other) {
            super(scalago.PingPong.SCHEMA$);
      if (isValidValue(fields()[0], other.counter)) {
        this.counter = data().deepCopy(fields()[0].schema(), other.counter);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'counter' field */
    public java.lang.Long getCounter() {
      return counter;
    }
    
    /** Sets the value of the 'counter' field */
    public scalago.PingPong.Builder setCounter(long value) {
      validate(fields()[0], value);
      this.counter = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'counter' field has been set */
    public boolean hasCounter() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'counter' field */
    public scalago.PingPong.Builder clearCounter() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'name' field */
    public java.lang.CharSequence getName() {
      return name;
    }
    
    /** Sets the value of the 'name' field */
    public scalago.PingPong.Builder setName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.name = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'name' field has been set */
    public boolean hasName() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'name' field */
    public scalago.PingPong.Builder clearName() {
      name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public PingPong build() {
      try {
        PingPong record = new PingPong();
        record.counter = fieldSetFlags()[0] ? this.counter : (java.lang.Long) defaultValue(fields()[0]);
        record.name = fieldSetFlags()[1] ? this.name : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
